BookShop/urls.py
from re import DEBUG
from django.contrib import admin
from django.urls import URLResolver, include, path
from django.conf.urls.static import static

from BookShop import settings


urlpatterns: list[URLResolver] = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import URLPattern, path
from catalog import views

app_name  = 'catalog'

urlpatterns: list[URLPattern] = [
    path('search/', views.catalog, name='search'),
    path('<slug:genre_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('authors/<slug:authors_slug>/', views.authors, name='authors'),
]

main/urls.py
from django.urls import URLPattern, path
from main import views

app_name  ='main'

urlpatterns: list[URLPattern] = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

users/urls.py
from django.urls import URLPattern, path
from users import views

app_name ='users'

urlpatterns: list[URLPattern] = [
    path('login', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profil_user/', views.profil_user, name='profil_user'),
    path('users-cart', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    image = models.ImageField(upload_to='users_images', blank=True, null=True, verbose_name='Фото пользователя')
    phone_number = models.CharField(max_length=10, blank=True, null=True, verbose_name='Номер телефона')

    
    class Meta:
        db_table = 'user'
        verbose_name = 'пользователя'
        verbose_name_plural = 'пользователи'
        
    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from users.models import User


class UserLoginForm(AuthenticationForm):

    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ['username', 'password']


class UserRegistrationForm(UserCreationForm):

    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'username',
            'email',
            'password1',
            'password2',
        )


class ProfileUserForm(UserChangeForm):

    image = forms.ImageField(required=False)
    first_name = forms.CharField()
    last_name = forms.CharField()
    username = forms.CharField()
    email = forms.CharField()

    class Meta:
        model = User
        fields = (
            'image',
            'first_name',
            'last_name',
            'username',
            'email',
        )

    

users/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.shortcuts import redirect, render
from carts.models import Cart
from orders.models import Order, OrderItem
from django.db.models import Prefetch

from users.forms import UserLoginForm, UserRegistrationForm, ProfileUserForm

def login(req):
    if req.method == 'POST':
        form = UserLoginForm(data=req.POST)
        if form.is_valid():
            username = req.POST['username']
            password = req.POST['password']
            user = auth.authenticate(username=username, password=password)

            session_key = req.session.session_key

            if user:
                auth.login(req, user)
                messages.success(req, f'{username}, Добро пожаловать!')

                if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

                redirect_page = req.POST.get('next', None)
                if redirect_page and redirect_page != reverse('user:logout'):
                    return HttpResponseRedirect(req.POST.get('next'))
                
                return HttpResponseRedirect(reverse('user:profil_user'))
    else:
        form = UserLoginForm()

    context = {
        'title': 'Авторизация',
        'form': form,
    }
    
    return render(req, 'users/login.html', context)



def registration(req):
    if req.method == 'POST':
        form = UserRegistrationForm(data=req.POST)
        if form.is_valid():
            form.save()

            session_key = req.session.session_key

            user = form.instance
            auth.login(req, user)

            if session_key:
                    Cart.objects.filter(session_key=session_key).update(user=user)

            messages.success(req, f'{user.username}, Регистрация прошла успешно! ')
            return HttpResponseRedirect(reverse('main:index'))
    else:
        form = UserRegistrationForm()

    context = {
        'title': 'Регистрация',
        'form': form,
    }
    
    return render(req, 'users/registration.html', context)

@login_required
def profil_user(req):
    if req.method == 'POST':
        form = ProfileUserForm(data=req.POST, instance=req.user, files=req.FILES)
        if form.is_valid():
            form.save()
            messages.success(req, 'Данные пользователя обновлены!')
            return HttpResponseRedirect(reverse('user:profil_user'))
    else:
        form = ProfileUserForm(instance=req.user)

        orders = (
            Order.objects.filter(user=req.user)
            .prefetch_related(
                Prefetch(
                    "orderitem_set",
                    queryset=OrderItem.objects.select_related("product"),
                )
            )
            .order_by("-id")
        )

    context = {
        'title': 'Личный кабинет',
        'form': form,
        "orders": orders,
    }
    
    return render(req, 'users/profil_user.html', context)


def users_cart(req):
    return render(req, 'users/users_cart.html')


@login_required
def logout(req):
    messages.success(req, f'{req.user.username}, До свидания!')
    auth.logout(req)
    
    return redirect(reverse('main:index'))

users/templates/users/login.html
{% extends "main/base.html" %}
{% load static %}

{% block content %}
<!-- Контент на странице -->
    <div class="row">
        <div class="container mt-5 text_user">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Авторизация</h2>
                    <form action="{% url 'user:login' %}" method="post">
                        {% csrf_token %}
                        {% if req.GET.next %}
                            <input type="hidden" name="next" value="{{ req.GET.next }}">
                        {% endif %}
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Имя пользователя</label>
                            <input type="text" class="form-control" 
                                value="{% if form.username.value %}{{ form.username.value }}{% endif %}" 
                                name="username" id="id_username" 
                                placeholder="Введите ваше имя пользователя" 
                                required>
                        </div>
                        <div class="mb-3">
                            <label for="id_password" class="form-label">Пароль</label>
                            <input type="password" class="form-control" 
                                name="password" 
                                id="id_password" 
                                placeholder="Введите ваш пароль" 
                                required>
                        </div>
                        <button type="submit" class="btn btn-dark btn-block">Войти</button> 
                    </form>
                    <div class="mt-3 text_user">
                        <a href="#">Забыли пароль?</a> | <a href="{% url 'users:registration' %}">Создать аккаунт</a>
                    </div>
                    <hr>
                    {% comment %} <div class="text-center">
                        <p>Или авторизуйтесь через:</p>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "deps/icons/google.svg" %}" alt="Catalog Icon" width="16" height="16">
                            Google
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "deps/icons/facebook.svg" %}" alt="Catalog Icon" width="16" height="16">
                            Facebook
                        </a>
                        <a href="#" class="btn btn-dark">
                            <img class="mx-1" src="{% static "deps/icons/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                            GitHub
                        </a>
                    </div> {% endcomment %}
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

users/templates/users/profil_user.html
{% extends "main/base.html" %}
{% load static %}
{% load carts_tags %}

{% comment %} {% block  modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock  %} {% endcomment %}

{% block content %}
    <!-- Контент на странице -->
    <div class="row">
        <div class="container mt-5">
            <div class="row">
                <!-- Профиль с данными пользователя -->
                <div class="col-md-5 text_user block1">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Профиль пользователя</h3>
                        <form action="{% url 'user:profil_user' %}" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-12 mb-3 text-center">
                                    {% if user.image %}
                                        <img src="{{ user.image.url }}"
                                            alt="Аватар пользователя" class="img-fluid rounded-circle"
                                            style="max-width: 150px;">
                                    {% else %}
                                    <img src="{% static "deps/images/baseavatar1.jpg" %}"
                                        alt="Аватар пользователя" class="img-fluid rounded-circle"
                                        style="max-width: 150px;">
                                    {% endif %}
                                    
                                    <input type="file" class="form-control mt-3" id="id_image"
                                        name="image"
                                        accept="image/*">
                                    {% if  form.image.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_first_name" class="form-label">Имя*</label>
                                    <input type="text" class="form-control" 
                                        id="id_first_name"
                                        name="first_name"
                                        placeholder="Введите ваше имя" 
                                        value="{{ form.first_name.value}}" 
                                        required>
                                    {% if  form.first_name.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                    {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_last_name" class="form-label">Фамилия*</label>
                                    <input type="text" class="form-control" 
                                        id="id_last_name"
                                        name="last_name"
                                        placeholder="Введите вашу фамилию" 
                                        value="{{ form.last_name.value}}" 
                                        required>
                                {% if  form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_username" class="form-label">Имя пользователя*</label>
                                    <input type="text" class="form-control" 
                                        id="id_username"
                                        name="username"
                                        placeholder="Введите ваше имя пользователя" 
                                        value="{{ form.username.value}}" 
                                        required>
                                    {% if  form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                                </div>
                                <div class="col-md-12 mb-3">
                                    <label for="id_email" class="form-label">Email*</label>
                                    <input type="email" class="form-control" 
                                        id="id_email"
                                        name="email"
                                        placeholder="Введите ваш email *youremail@example.com" 
                                        value="{{ form.email.value}}"
                                        required>
                                    {% if  form.email.errors %}
                                        <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                    {% endif %}
                                </div>
                            </div>
                            <button type="submit" class="btn btn-dark">Сохранить</button>
                        </form>
                    </div>
                </div>
                <!-- Корзина -->
                {% user_carts request as carts %}
                {% comment %} <div class="col-md-7">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4 text_user">Корзина</h3>
                        <div class="container" id="cart-items-container">
                            <!-- Разметка корзины -->
                            {% include 'carts/includes/included_cart.html' %}
                            <!-- Закончилась разметка корзины -->
                        </div>
                   
                    </div>
                </div> {% endcomment %}
                  <!-- Оформленные заказы -->
                 <div class="col-md-12 block2">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4 text_user">Мои заказы</h3>
                        <!-- Разметка заказов -->
                        <div class="container">
                            <div class="accordion" id="accordionExample">
                                {% for order in orders %}
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="heading{{ order.id }}">
                                        <div class="accordion-button">
                                            Заказ № {{ order.id }} - <br> {{ order.created_timestamp }}</strong>
                                            <table class="table table-dark table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>Товар</th>
                                                        <th>Количество</th>
                                                        <th>Цена</th>
                                                        <th>Стоимость товара(с учетом скидки)</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for item in order.orderitem_set.all %}
                                                    <tr>
                                                        <td><a class="text-white" href="{% url 'catalog:product' item.product.slug %}">{{ item.product.title }}</a></td>
                                                        <td>{{ item.quantity }}</td>
                                                        <td>{{ item.product.price }}</td>
                                                        <td>{{ item.price }}</td>
                                                    </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                        </div>
                                    </h2>
                                    <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <!-- Код тела аккордеона -->
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        
                        <!-- Закончилась разметка заказов -->  



                <!-- Оформленные заказы -->
                {% comment %} <div class="col-md-12">
                    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                        <h3 class="text-center mb-4">Мои заказы</h3>
                        <!-- Разметка заказов -->
                        <div class="container">
                            <div class="accordion" id="accordionExample">
                                {% for order in orders %}
                                <div class="accordion-item">
                                    <h2 class="accordion-header" id="heading{{ order.id }}">
                                        <button class="accordion-button {% if order != orders.0 %}collapsed{% endif %}" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ order.id }}" aria-expanded="false" aria-controls="collapse{{ order.id }}">
                                            Заказ № {{ order.id }} - {{ order.created_timestamp }} | Статус: <strong class="mx-2">{{ order.status }}</strong>
                                        </button>
                                    </h2>
                                    <div id="collapse{{ order.id }}" class="accordion-collapse collapse {% if order == orders.0 %}show{% endif %}" aria-labelledby="heading{{ order.id }}" data-bs-parent="#accordionExample">
                                        <div class="accordion-body">
                                            <table class="table table-dark table-hover">
                                                <thead>
                                                    <tr>
                                                        <th>Товар</th>
                                                        <th>Количество</th>
                                                        <th>Цена</th>
                                                        <th>Общая стоимость (с учетом скидки)</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    {% for item in order.orderitem_set.all %}
                                                    <tr>
                                                        <td><a class="text-white" href="{% url 'catalog:product' item.product.slug %}">{{ item.product.title }}</a></td>
                                                        <td>{{ item.quantity }}</td>
                                                        <td>{{ item.product.price }}</td>
                                                        <td>{{ item.price }}</td>
                                                    </tr>
                                                    {% endfor %}
                                                </tbody>
                                            </table>
                                                <div class="d-flex justify-content-between">
                                                <p><strong>Итого:</strong></p>
                                                <p><strong>{{ order.total_cost }} ₽</strong></p>
                                            </div>                                             
                                        </div>
                                    </div>
                                </div>
                                {% endfor %}
                            </div>
                        </div>
                        <!-- Закончилась разметка заказов -->  {% endcomment %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

users/templates/users/registration.html
{% extends "main/base.html" %}
{% load static %}

{% comment %} {% block  modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock  %} {% endcomment %}

{% block content %}
    <!-- Контент на странице -->
    <div class="row">
        <div class="container mt-5 text_user">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Регистрация</h2>
                    <form action="{% url 'user:registration' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Имя*</label>
                                <input type="text" class="form-control" 
                                    id="id_first_name"
                                    value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" 
                                    name="first_name"
                                    placeholder="Введите ваше имя" 
                                    required>
                            {% if  form.first_name.errors %}
                                <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                            {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Фамилия*</label>
                                <input type="text" class="form-control" 
                                    id="id_last_name"
                                    value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" 
                                    name="last_name"
                                    placeholder="Введите вашу фамилию" 
                                    required>
                                {% if  form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">Имя пользователя*</label>
                                <input type="text" class="form-control" 
                                    id="id_username"
                                    name="username"
                                    value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                    placeholder="Введите ваше имя пользователя" 
                                    required>
                                {% if  form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control"
                                    id="id_email"
                                    name="email"
                                    value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                    placeholder="Введите ваш email" 
                                    required>
                                {% if  form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Пароль*</label>
                                <input type="password" class="form-control" 
                                    id="id_password1"
                                    name="password1"
                                    value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                    placeholder="Введите пароль" 
                                    required>
                                {% if  form.password1.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password2" class="form-label">Подтверждение пароля*</label>
                                <input type="password" class="form-control" 
                                    id="id_password2"
                                    name="password2"
                                    value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                    placeholder="Подтвердите пароль" 
                                    required>
                                {% if  form.password2.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                            class="btn btn-dark btn-block">Зарегистрироваться</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}

users/templates/users/users_cart.html
{% extends "main/base.html" %}
{% load static %}
{% load carts_tags %}

{% block content %}
{% user_carts request as carts %}
     <!-- Контент на странице -->
     <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4 text_user">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include 'carts/includes/included_cart.html' %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock  %}