BookShop/urls.py
from re import DEBUG
from django.contrib import admin
from django.urls import URLResolver, include, path
from django.conf.urls.static import static

from BookShop import settings


urlpatterns: list[URLResolver] = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalog/urls.py
from django.urls import URLPattern, path
from catalog import views

app_name  = 'catalog'

urlpatterns: list[URLPattern] = [
    path('search/', views.catalog, name='search'),
    path('<slug:genre_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('authors/<slug:authors_slug>/', views.authors, name='authors'),
]

main/urls.py
from django.urls import URLPattern, path
from main import views

app_name  ='main'

urlpatterns: list[URLPattern] = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

users/urls.py
from django.urls import URLPattern, path
from users import views

app_name ='users'

urlpatterns: list[URLPattern] = [
    path('login', views.login, name='login'),
    path('registration/', views.registration, name='registration'),
    path('profil_user/', views.profil_user, name='profil_user'),
    path('users-cart', views.users_cart, name='users_cart'),
    path('logout/', views.logout, name='logout'),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.http import HttpResponse
from django.shortcuts import render
from catalog.models import Genres


def index(req):
    # genres = Genres.objects.all()

    context = {
        'title': 'HOME - ГЛАВНАЯ',
        'content': 'МИР КНИГ!', 
        # 'genres': genres
    }

    return render(req, 'main/index.html', context)

def about(req):
    context = {
        'title': 'HOME - О НАС',
        'content': 'О НАС',
        'text_on_page': 'Излишне говорить, что вы лишаете себя настоящего читательского удовольствия, проходя мимо таких произведений!'
    }

    return render(req, 'main/about.html', context)

def contact(req):
    context = {
        'title': 'HOME - КОНТАКТЫ',
        'content': 'О НАС',
    }

    return render(req, 'main/contact.html', context)

main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block  css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock  %}

{% comment %} {% block  modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock  %} {% endcomment %}

{% block content %}
    
    <div class="text_glava">
        <h1 class="text_glava"><i><strong> {{ content }} </strong></i></h1>
        <br>
        <h4 class='text_glava'> Мы - магазин книг, который предлагает широкий выбор книг разных жанров и авторов. Мы стремимся предоставлять нашим клиентам качественные издания и отличный сервис. В нашем магазине вы найдете как новинки, так и классические произведения мировой литературы. </h4>
        <br>
        <h4 class='text_glava'> Не стесняйтесь посетить наш магазин и окунуться в мир книг!</h4>
    </div>
    <br>
    <!-- Карусель -->
<div id="demo" class="carousel slide" data-bs-ride="carousel">

    <!-- Индикаторы/точки-->
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
      <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
    </div>
    
    <!-- The slideshow/carousel -->
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="{% static "/deps/images/1.jpg" %}" alt="Los Angeles" class="d-block" style="width:30%">
        <div class="carousel-caption">
            <br>
          <h3>Лицензия онлайн-магазина "МИР КНИГ"</h3>
        </div>
      </div>
      <div class="carousel-item">
        <img src="{% static "/deps/images/2.jpg" %}" alt="Chicago" class="d-block" style="width:30%">
        <div class="carousel-caption">
            <br>
          <h3>Грамота о лучшем онлайн-магазине</h3>
        </div> 
      </div>
    </div>
    
    <!-- Left and right controls/icons -->
    <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
      <span class="carousel-control-prev-icon"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
      <span class="carousel-control-next-icon"></span>
    </button>
  </div>
{% endblock  %}

{% block footer %}
    <footer class="bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">BOOK &copy; Studio 2024</p>
        </div>
    </footer>
{% endblock  %}

main/templates/main/base.html
{% load static %}
{% load catalog_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}"> 
    <link rel="stylesheet" href="{% static "deps/css/my_catalog.css" %}"> 
    <!-- Стиль footer-a для главной страницы -->
   {% block  css %}

   {% endblock %}
    <!-- Favicons for different platforms -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static "deps/favicon/apple-touch-icon.png" %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static "deps/favicon/favicon-32x32.png" %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static "deps/favicon/favicon-16x16.png" %}">
    <link rel="manifest" href="{% static "deps/favicon/site.webmanifest" %}">
    <title> {{ title }} </title>
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-dark" data-bs-theme="dark">
            <div class="container">
                <a class="navbar-brand" id="home" href="{% url 'main:index' %}">ГЛАВНАЯ</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                Информация
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="{% url 'main:contact' %}">Контактная информация</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'main:about' %}">Про нас</a></li>
                            </ul>
                        </li>
                        {% if not user.is_authenticated %}  
                            <li class="nav-item">
                                <a class="nav-link  text-white" href="{% url 'users:login' %}">Войти</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown ">
                                <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                    data-bs-toggle="dropdown" aria-expanded="false">
                                    Мой профиль
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item  text-white " href="{% url 'users:profil_user' %}">Личный кабинет</a>
                                    </li>
                                    <li><a class="dropdown-item  text-white " href="{% url 'users:users_cart' %}">Корзина</a>
                                    </li>
                                    {% if user.is_admin or user.is_staff %}
                                        <li>
                                            <a class="dropdown-item  text-white" href="{% url "admin:index"%}">Админ панель</a></li>
                                        <li>
                                    {% endif %}
                                        <hr class="dropdown-divider">
                                    </li>
                                    <li><a class="dropdown-item  text-white" href="{% url 'users:logout' %}">Выйти</a></li>
                                </ul>
                            </li>
                        {% endif %}
                    </ul>
                   <div class="poisk"> 
                        <form class="d-flex" role="search" action="{% url  'catalog:search' %}" method="get">
                            <input class="form-control me-2" type="search" name="q" placeholder="Введите слово или цифру" aria-label="Search">
                            <button class="btn btn-outline-success text-white" type="submit">Поиск</button>
                        </form> 
                    </div>  
                </div>
            </div>
        </nav>
    </header>
    <section>
        <div class="container">
            <!-- Каталог и корзина с фиксированным расположением на странице -->
<div class="mt-1 position-fixed z-3">
    <!-- Каталог -->
    <div class="menu">
		<div class="title"><h1>КАТАЛОГ</h1></div>
		<div class="list_menu">
            <ul>
                {% tag_genres as genres %}
                {% for genre in genres %}
                    <li>
                        <span><a class="text-white" href="{% url 'catalog:index' genre.slug %}">{{ genre.title}}</a></span>
                    </li>
                {% endfor%}
            </ul>
		</div>
        <img class="img_book" src="{% static "/deps/images/book.png" %}" alt="Book">
	</div>
 
    <!-- Значек корзины, вызывает модальное окно -->
    {% block  modal_cart %}{% endblock  %}
    <!-- Закончилась разметка модального окна -->
</div>
{% comment %} работает через кнопку, то что ниже {% endcomment %}
            {% comment %} <!-- Каталог и корзина с фиксированным расположением на странице -->
            <div class="row mt-1 position-fixed z-3">
                <!-- Каталог -->
                <div class="dropdown mb-2">
                    <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        Каталог
                        <img class="mx-1" src="{% static "deps/icons/grid-fill.svg" %}" alt="Catalog Icon" width="16"
                            height="16">
                    </button>

                    <ul class="dropdown-menu bg-dark" data-bs-theme="dark">
                        {% tag_genres as genres %}
                        {% for genre in genres %} 
                            <li>
                                <a class="dropdown-item text-white" href="{% url 'catalog:index' genre.slug %}">{{ genre.title}}</a>
                            </li>
                        {% endfor%}
                    </ul>
                </div>
                <!-- Значек корзины, вызывает модальное окно -->
                    {% block  modal_cart %}{% endblock  %}
                <!-- Закончилась разметка модального окна -->
            </div>  {% endcomment %}
        </div> 
        <!-- Контент -->
        <div class="container">
            <div class="row mt-1">
                <div class="col-lg-2">
                    <!-- Пустой блок на Ваше усмотрение -->
                </div>
                <div class="col-lg-10">
                    <!-- Контент на странице -->
                    {% include "includes/notifications.html" %}
                    {% block  content %}

                    {% endblock  %}
                </div>
            </div>
        </div>
    </section>
    {% block footer %}

    {% endblock %}
    <script src="{% static "deps/js/jquery/jquery-3.7.0.min.js" %}"></script>
    <script src="{% static "deps/js/jquery-ajax.js" %}"></script>
    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js"%}"></script>
    <script src="{% static "deps/js/maps.js" %}"></script>
</body>

</html>

main/templates/main/contact.html
{% extends "main/base.html" %}
{% load static %}

{% block  css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock  %}

{% comment %} {% block  modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock  %} {% endcomment %}

{% block content %}
<div class="text_glava">
    <h1 class="text_glava"><i><strong> Контактная информация </strong></i></h1>
    <div id="text_p">
        <h3 class='text_glava'> Наш телефон:</h3>
        <h4 class='text_glava'> +7 800 707-37-27, звонок по РФ бесплатный.</h4>
        <br> 
        <h3 class='text_glava'> Наша электронная почта:</h3>
        <h4 class='text_glava'>hello_book@mail.ru</h4>
    </div>
    <br>
    <div id="text_p">
        <h3 class='text_glava'> Время работы:</h3>
        <h4 class='text_glava'> 
            Мы работаем с 10 до 20 по Московскому времени. Если вы позвонили в нерабочее время, мы с вами свяжемся утром следующего рабочего дня. Сообщения обрабатываются тоже в рабочее время.
            </h4>
    </div>
        <br>
        <div id="text_p">
            <h3> Расположение главного офиса :</h3>
        <div id="map-test" class="map"></div>
        <script src="https://api-maps.yandex.ru/2.1/?apikey=4d3da9b5-6251-4a68-a6ea-33ab99c73806&lang=ru_RU"></script>
        <br>   
    </div>
    
    {% comment %} <div id="map" style="width: 600px; height: 400px">

    </div> {% endcomment %}
</div>
{% endblock  %}

{% block footer %}
    <footer class="bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">BOOK &copy; Studio 2024</p>
        </div>
    </footer>
{% endblock  %}

main/templates/main/index.html
{% extends "main/base.html" %}
{% load static %}

{% block  css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock  %}

{% comment %} {% block  modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock  %} {% endcomment %}

{% block content %}
    <h3 class="text_glava">
        <strong>
            <h1 class="mt-5 pt-5"><strong> {{content}} </strong></h1>
         </strong>
    </h3>
    <br>
    <br>
    <h3 class="text_glava"><i><strong> Мир Книг </strong></i> - это не просто магазин, это целая вселенная, полная захватывающих историй и новых знаний. Погрузитесь в неё вместе с нами!
        <br>
        <br>У нас есть всё: от классической литературы до современных бестселлеров, от научной фантастики до учебников.
        <br>
        <br>Добро пожаловать в наш уникальный онлайн-магазин!
        <br>
        <br>
        <br>
        <strong><i class="your-text-class">"Тот, кто не читает, не имеет преимуществ перед тем, кто не умеет читать."</i></strong></h3>
{% endblock  %}

{% block footer %}
    <footer class="bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">BOOK &copy; Studio 2024</p>
        </div>
    </footer>
{% endblock  %}