BookShop/urls.py
from re import DEBUG
from django.contrib import admin
from django.urls import URLResolver, include, path
from django.conf.urls.static import static

from BookShop import settings


urlpatterns: list[URLResolver] = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import URLPattern, path
from carts import views

app_name ='carts'

urlpatterns = [
    path('cart_add/', views.cart_add, name='cart_add'),
    path('cart_change/', views.cart_change, name='cart_change'),
    path('cart_remove/', views.cart_remove, name='cart_remove'),
]

catalog/urls.py
from django.urls import URLPattern, path
from catalog import views

app_name  = 'catalog'

urlpatterns: list[URLPattern] = [
    path('search/', views.catalog, name='search'),
    path('<slug:genre_slug>/', views.catalog, name='index'),
    path('product/<slug:product_slug>/', views.product, name='product'),
    path('authors/<slug:authors_slug>/', views.authors, name='authors'),
]

main/urls.py
from django.urls import URLPattern, path
from main import views

app_name  ='main'

urlpatterns: list[URLPattern] = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from users.models import User

class Genres(models.Model):
    title = models.CharField(max_length=150, unique=True, verbose_name='Жанр книги')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        ordering = ['title']
        db_table = 'genre'
        verbose_name = 'жанр'
        verbose_name_plural = 'Жанры'

    def __str__(self):
        return self.title 


class Languages(models.Model):
    name = models.CharField(max_length=30, unique=True, verbose_name='Язык книги')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        ordering = ['name']
        db_table = 'language'
        verbose_name = 'язык'
        verbose_name_plural = 'Языки'

    def __str__(self):
        return self.name


class Publishers(models.Model):
    name = models.CharField(max_length=30, verbose_name='Издательство')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')

    class Meta:
        ordering = ['name']
        db_table = 'publisher'
        verbose_name = 'издательство'
        verbose_name_plural = 'Издательства'

    def __str__(self):
        return self.name 


class Authors(models.Model):
    last_name = models.CharField(max_length=300, verbose_name='ФИО автора')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    date_of_birth = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    description = models.TextField(blank=True, null=True, verbose_name='Сведения об авторе')
    photo = models.ImageField(upload_to='catalog_photo', blank=True, null=True, verbose_name='Фото автора')
   

    class Meta:
        ordering = ['last_name']
        db_table = 'author'
        verbose_name = 'автор'
        verbose_name_plural = 'Авторы'
        
    def __str__(self):
        return self.last_name


class Products(models.Model):
    title = models.CharField(max_length=200, unique=True, verbose_name='Название книги')
    slug = models.SlugField(max_length=200, unique=True, blank=True, null=True, verbose_name='URL')
    genre = models.ForeignKey(to=Genres, on_delete=models.CASCADE, verbose_name='Жанр книги', null=True)
    language = models.ForeignKey(to=Languages, on_delete=models.CASCADE, verbose_name='Язык книги', null=True)
    publisher = models.ForeignKey(to=Publishers, on_delete=models.CASCADE, verbose_name='Издательство', null=True)
    year_publication = models.CharField(max_length=4, verbose_name='Год издания')
    author = models.ManyToManyField(to=Authors, verbose_name='Автор(ы) книги')
    summary = models.TextField(blank=True, null=True, verbose_name='Аннотация книги')
    isbn = models.CharField(max_length=15, unique=True, verbose_name='ISBN  книги')
    image = models.ImageField(upload_to='catalog_images', blank=True, null=True, verbose_name='Изображение обложки книги')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=4, decimal_places=0, verbose_name='Скидка в %')
    quantity = models.PositiveBigIntegerField(default=0, verbose_name='Количество')
    age_limit = models.PositiveSmallIntegerField(default=0, verbose_name='Ограничение по возрасту')

    class Meta:
        ordering = ['title']
        db_table = 'product'
        verbose_name = 'товар'
        verbose_name_plural = 'Товары'
        ordering = ("id",)

    def __str__(self):
        return f'{self.title} Количество - {self.quantity}'
    
    def get_absolute_url(self):
        return reverse("catalog:product", kwargs={"product_slug": self.slug})

    def display_id(self):
        return f'{self.id:05}'
    
    
    def calculate_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount/100, 2)
        
        return self.price


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    product = models.ForeignKey(Products, on_delete=models.CASCADE)
    body = models.TextField(verbose_name='ОТЗЫВ')
    active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'комментарий'
        verbose_name_plural = 'комментарии'

    def __str__(self):
        return f'Комментарий от {self.user} к {self.product}'

catalog/forms.py
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['body']

catalog/views.py
from django.shortcuts import get_list_or_404, render
from django.core.paginator import Paginator
from catalog.models import Authors, Products, Comment
from catalog.utils import q_search
from django.shortcuts import render
from .forms import CommentForm
from .models import Comment


def catalog(req, genre_slug=None):

    page = req.GET.get('page', 1)
    sale = req.GET.get('sale', None)
    order = req.GET.get('order', None)
    age_limit = req.GET.get('age_limit', None)
    query = req.GET.get('q', None)

    if genre_slug == 'all':
        goods = Products.objects.all()
    elif query:
        goods = q_search(query)
    else:
        goods = get_list_or_404(Products.objects.filter(genre__slug=genre_slug))
    

    if sale:
        goods = goods.filter(discount__gt=0)
    if order and order != 'default':
        goods = goods.order_by(order)
    if age_limit:
        goods = goods.filter(age_limit=age_limit)


    paginator = Paginator(goods, 3)
    current_page = paginator.page(int(page))


    context = {
        "title": "HOME - КАТАЛОГ",
        "goods": current_page, 
        'slug_url': genre_slug,
    }

    return render(req, "catalog/catalog.html", context)



def proverkaComm(newcom):
    blacklist = ['жопа', 'херня',]
    spisok = newcom.body.lower().split()

    for one in spisok:
        if one in blacklist:
            newcom.active = False
            newcom.save()
            return False

    previous_com = Comment.objects.filter(user=newcom.user).order_by('-created_at').first()
    if previous_com and previous_com.body.lower() == newcom.body.lower():
        newcom.active = False
        newcom.save()
        return False

    newcom.active = True
    newcom.save()


def product(req, product_slug):
    product = Products.objects.get(slug=product_slug)
    author = product.author.all()

    if req.method == 'POST' and req.user.is_authenticated: 
        comment_form = CommentForm(req.POST)
        if comment_form.is_valid():
            newcom = comment_form.save(commit=False)
            newcom.product = product
            newcom.user = req.user
            if proverkaComm(newcom):
                newcom.save()

    # обираем комментарии после возможного создания нового комментария
    comment = product.comment_set.filter(active=True)
    comment_form = CommentForm()  # форма была доступна только авторизованным пользователям

    context = {
        "product": product,
        'author': author,
        'comments': comment,
        'comment_form': comment_form if req.user.is_authenticated else None  
    }

    # Вывод информации
    print('Product: ', product)
    print('Authors: ', author)
    print('Comment: ', comment)
    print('Comment Form: ', comment_form)

    return render(req, "catalog/product.html", context=context)



def authors(req, authors_slug):
    authors = Authors.objects.get(slug=authors_slug)

    context = {
        "authors": authors,
    }

    return render(req, "catalog/authors.html", context=context)

















# РАБОЧИЯ ФУНКЦИЯ
# def product(req, product_slug):
#     product = Products.objects.get(slug=product_slug)

#     author = product.author.all()

#     context = {
#         "product": product,
#         'author': author
#     }

#     # Вывод информации
#     print('Product: ', product)
#     print('Authors: ', author)

#     return render(req, "catalog/product.html", context=context)





























# def proverkaComm(newcom):
#     blacklist = ['жопа', 'сука', 'херня', 'блять']
#     spisok = newcom.body.lower().split()

#     for one in spisok:
#         if one in blacklist:
#             newcom.delete()
#             return False

#     previous_com = Comment.objects.filter(user=newcom.user).order_by('-created_at').first()
#     if previous_com and previous_com.body.lower() == newcom.body.lower():
#         newcom.delete()
#         return False

#     newcom.active = True
#     newcom.save()
#     return True

# def add_comment(request):
#     if request.method == 'POST':
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.user = request.user
#             if proverkaComm(comment):
#                 return redirect('some_view')
#     else:
#         form = CommentForm()
#     return render(request, 'add_comment.html', {'form': form})

catalog/templates/catalog/authors.html
{% extends "main/base.html" %}
{% load static %}

{% block  content %}
    <!-- Контент на странице -->
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow" id="conteiner_my">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    {% if authors.photo and authors.photo.url %}
                        <img src="{{ authors.photo.url }}" class="card-img-top"  id="image-radius" alt="{{authors.last_name}}">
                    {% else %}
                        <img src="{% static "/deps/images/Not found image_auther.png" %}" class="card-img-top" id="image-radius" alt="...">
                    {% endif %}
                </div>
                
              
            <!-- Описание товара -->
            <div class="card-body">
                <h5 class="card-text"><strong>ФИО: </strong> {{ authors.last_name }} </h5>
                <h5 class="card-text"><strong>Год рождения: </strong> {{ authors.date_of_birth }}</h5>
                <h5 class="card-text"><strong>Краткая информация об авторе:</strong> {{ authors.description }}</h5>
                
            </div>
        </div>
    </div>
{% endblock  %}

catalog/templates/catalog/catalog.html
{% extends "main/base.html" %}
{% load static %}
{% load catalog_tags %}

{% block  modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock  %}

{% block  css %}
    <link rel="stylesheet" href="{% static "deps/css/my_footer_css.css" %}">
{% endblock  %}


{% block  content %}
    <div class="row">
        <!-- Форма фильтров -->
        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Фильтры
            </button>

            <form action="{% if request.GET.q %}{% url 'catalog:search' %}{% else %}{% url 'catalog:index' slug_url %}{% endif %}" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="checkbox" name="sale" id="flexCheckDefault" value="on" {% if request.GET.sale == 'on' %}checked{% endif %}>

                    {% if request.GET.q %}
                        <input type="hidden" name="q" value="{{ request.GET.q }}">
                    {% endif %}

                    <label class="form-check-label" for="flexCheckDefault">
                        Товары по акции
                    </label>
                </div>

                <p class="text-white mx-3 mt-3">Сортировать:</p>

                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order" id="flexRadioDefault1" value="default"
                        {% if not request.GET.order or request.GET.order == 'default' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>

                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order" id="flexRadioDefault2" value="price" 
                        {% if request.GET.order == 'price' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        От дешевых к дорогим
                    </label>
                </div>

                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order" id="flexRadioDefault3" value="-price" 
                        {% if request.GET.order == '-price' %}checked{% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        От дорогих к дешевым
                    </label>
                </div>
            
                <div class="form-group">
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="age_limit" id="ageLimitUnder18" value="18"
                            {% if request.GET.age_limit == '18' %}checked{% endif %}>
                        <label class="form-check-label" for="ageLimitUnder18">
                            Книги 18+
                        </label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="age_limit" id="ageLimitUnder16" value="16"
                            {% if request.GET.age_limit == '16' %}checked{% endif %}>
                        <label class="form-check-label" for="ageLimitUnder16">
                            Книги 16+
                        </label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="age_limit" id="ageLimitUnder16" value="12"
                            {% if request.GET.age_limit == '12' %}checked{% endif %}>
                        <label class="form-check-label" for="ageLimitUnder16">
                            Книги 12+
                        </label>
                    </div>
                    <div class="form-check text-white mx-3">
                        <input class="form-check-input" type="radio" name="age_limit" id="ageLimitNoLimit" value="0"
                            {% if request.GET.age_limit == '0' %}checked{% endif %}>
                        <label class="form-check-label" for="ageLimitNoLimit">
                            Без ограничений
                        </label>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
            </form>
        </div>

        
            {% if request.GET.q %}
                <h3 class="mt-4 poisk_text">Результаты поиска по запросу <strong><i>{{request.GET.q}}</i></strong> </h3>
            {% if not goods %}
                
                <h2 class="mt-4 poisk_text"> Ничего не найдено. </h2>
      
        {% endif %}
        {% endif%}
        {% for product in goods %}
            <!-- Карта товара -->
            <div class="col-lg-4 col-md-6 p-4">
                <div class="card border-primary rounded custom-shadow">
                    {% if product.image %}
                        <img src="{{product.image.url}}" class="card-img-top" alt="{{product.title}}">
                    {% else %}
                        <img src="{% static "/deps/images/Not found image.png" %}" class="card-img-top" alt="...">
                    {% endif %}

                    <div class="card-body" id="text_catalog">
                        <a href="{% url 'catalog:product' product.slug %}">
                            <p class="card-title">{{ product.title|truncatechars:33 }}</p>
                        </a>
                        <p class="card-text">{{ product.summary|truncatechars:50}}</p>
                        <p class="card-text text-truncate">{{ product.age_limit }} +</p>
                        {% comment %} <p class="product_id">id: {{ product.display_id }}</p> {% endcomment %}
                        <div class="d-flex justify-content-between">

                            {% if product.discount %}
                                <p><s>{{ product.price }} </s> ₽ </p>
                                <p><strong>{{ product.calculate_price }} ₽</strong></p>
                                <span class="badge bg-warning text-dark"> - {{ product.discount }} %</span>
                            {% else %}
                                <p><strong>{{ product.price }} ₽</strong></p>
                            {% endif %}
                            
                            <a href="{% url 'cart:cart_add' %}" class="btn add-to-cart" 
                            data-product-id="{{ product.id }}">
                                {% csrf_token %}
                                <img class="mx-1" src="{% static "/deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                                    width="32" height="32">
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}


    </div>
    <!-- Пагинация -->
    {% if goods %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center my-4">
                <div class="custom-shadow d-flex">
                    <li class="page-item {% if not goods.has_previous %} disabled {% endif %}">
                    <a class="page-link" href="{% if goods.has_previous %}?{% chang_params page=goods.previous_page_number %}{% else %}#{% endif %}">Предыдущая</a>
                    </li>

                    {% for page in goods.paginator.page_range%}
                    {% if page >= goods.number|add:-2 and page <= goods.number|add:2 %}
                        <li class="page-item {% if goods.number == page %} active {% endif %}">
                            <a class="page-link" href="?{% chang_params page=page %}">{{page}}</a>
                        </li>
                    {% endif %}
                    {% endfor %}


                    <li class="page-item {% if not goods.has_next %} disabled {% endif %}">
                        <a class="page-link" href="{% if goods.has_next %}?{% chang_params page=goods.next_page_number %}{% else %}#{% endif %}">Следующая</a>
                    </li>
                </div>
            </ul>
        </nav>
    {% endif %}
{% endblock  %}

{% block  footer %}
    <footer class="bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">BOOK &copy; Studio 2024</p>
        </div>
    </footer>
{% endblock  %}

catalog/templates/catalog/product.html
{% extends "main/base.html" %}
{% load static %}

{% block  modal_cart %}
{% include 'includes/cart_button.html' %}
{% endblock  %}

{% block  content %}
    <!-- Контент на странице -->
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow" id="conteiner_my">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    <img src="{{ product.image.url }}" class="card-img-top" data-bs-toggle="modal" data-bs-target="#imageModal1" id="image-radius">
                </div>
                <div class="col-md-4 ">
                    {% comment %} <p class="product_id mt-3">id: {{ product.display_id }}</p> {% endcomment %}
                </div>
                <!-- Увеличить изображение в модальном окне -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                    aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">{{ product.title }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ product.image.url }}"
                                    class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Описание товара -->
            <div class="card-body">
                <h5 class="card-text"><strong>Цена:</strong> {{ product.calculate_price }} ₽</h5>
                <h5 class="card-title"><strong>Название книги:</strong> {{ product.title }}</h5>
                <h5 class="card-title"><strong>Автор:</strong>
                    {% for author in product.author.all %}
                        {% if "Нет данных" in author.last_name %}
                            {{ author.last_name }}
                        {% else %}
                            <a href="{% url 'catalog:authors' author.slug %}">{{ author.last_name }}</a>
                        {% endif %}
                    {% endfor %}
                </h5>
                <h5 class="card-text"><strong>Язык:</strong> {{ product.language }} </h5>
                <h5 class="card-text"><strong>ISBN:</strong> {{ product.isbn }}</h5>
                <h5 class="card-text"><strong>Издательство:</strong> {{ product.publisher}}</h5>
                <h5 class="card-text"><strong>Год издательство:</strong> {{ product.year_publication }}</h5>
                <h5 class="card-text"><strong>Ограничение по возрасту:</strong> {{ product.age_limit }} + </h5>
                <h5 class="card-text"><strong>Аннотация книги:</strong> {{ product.summary }}</h5>
               
                <a href="{% url 'cart:cart_add' %}" class="btn btn-dark add-to-cart"
                data-product-id="{{ product.id }}">
                {% csrf_token %}
                Добавить в корзину</a>
                <div class="hr"></div>
               <div class="">
                {% if comment_form %}
                    <form method="POST" class="form-group">
                        {% csrf_token %}
                        <h5 class="card-title"><strong>{{ comment_form.as_p }}</strong></h5>
                        <button type="submit" class="btn btn-dark btn-block">Оставить отзыв</button>
                    </form>
                {% else %}
                <h5 class="card-title"><strong>ВЫ ДОЛЖНЫ ВОЙТИ, ЧТОБЫ ОСТАВИТЬ ОТЗЫВ.</strong></h5>
                {% endif %}

                <div><br></div>
                <div class="comment-block">
                    {% for comment in comments %}
                        <div class="card mb-3">
                            <div class="">
                                <h5 class="card-title"> <strong>Пользователь: </strong> {{ comment.user.username }}</h5>
                                <h6 class="card-subtitle mb-2 text-muted">{{ comment.created_at }}</h6>
                                <p class="card-text">{{ comment.body }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock  %}